---

- name: ensure that br_netfilter module is loaded
  modprobe:
    name: br_netfilter
    state: present

- name: set up some kernel settings for vpn to 1
  sysctl: 
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.conf
    sysctl_set: yes
  with_items:
    - "net.ipv4.ip_forward"
    - "net.ipv6.conf.default.forwarding"
    - "net.ipv6.conf.all.forwarding"
    - "net.ipv4.conf.all.rp_filter"
    - "net.ipv4.conf.default.send_redirects"

- name: set up some kernel settings for vpn to 0
  sysctl: 
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.conf
    sysctl_set: yes
  with_items:
    - "net.ipv4.conf.default.proxy_arp"
    - "net.ipv4.conf.all.send_redirects"