---

- name: Check if /etc/rc.local is already created
  stat:
    path: /etc/rc.local
  register: rclocal_exist

- name: create /etc/rc.local
  file:
    path: /etc/rc.local
    state: touch
    owner: root
    group: root
    mode: '0755'
  when: not rclocal_exist.stat.exists

- name: line in rc.local
  lineinfile:
    path: /etc/rc.local
    line: "#!/bin/bash"
    
- name: line in rc.local
  lineinfile:
    path: /etc/rc.local
    line: "/etc/firewall.sh"

- name: create firewall rules script
  template:
    src: firewall.sh.j2
    dest: /etc/firewall.sh
    owner: root
    group: root
    mode: '0755'